### PR TITLE
Only load enabled extension packages

### LINKED ISSUE #1177: Jupyter Server imports extensions even when they are disabled, slowing down startup
## Description

jupyter server will do an import of the *python* package for *all* extensions, even if they are explicitly disabled. This can cause a big performance penalty, as well as cause code to execute that perhaps shouldn't be.

## Reproduce

1. Install `jupyter_server` on a fresh virtualenv / conda env
2. Install the `panel` package, as that provides a server extension that takes a while to start
3. Run `jupyter server extension list` to make sure that `panel.io.jupyter_server_extension` is enabled
4. Disable it with `jupyter server extension disable panel.io.jupyter_server_extension`, and verify with `jupyter server extension list` again
5. Start `jupyter server`

## Expected behavior

The `panel.io.jupyter_serverextension` package is *not* imported, and the line `Package panel.io.jupyter_server_extension took 0.4643s to import` is not printed by `jupyter-server` on startup. The extension is disabled, and should not be imported.

Instead, the line is printed as the python package is imported anyway.

## Context

This came up in the context of debugging https://github.com/2i2c-org/infrastructure/issues/2047, where I was trying to figure out why jupyter server startup was so slow jupyterhub was timing out at 30s for the *python process* to startup after the container has started. I was testing by assuming that disabling an extension wouldn't import it, both as it is the least surprising behavior but also because that is how notebook server behaves. Eventually `strace` output led me to realize that disabling extenions doesn't stop them from being imported.

While https://github.com/jupyter-server/jupyter_server/pull/1176 and https://github.com/jupyter-server/jupyter_server/pull/1171
make it easier to see which packages are adding startup latency, it is still impossible to disable an extension temporarily to remove the latency issue. The only way to reduce latency from panel's serverextension is to *entirely uninstall panel*, which breaks other functionality too.

Given that enable / disable status can be determined without having to import the python package, no import should ideally be done if the extension itself is disabled.

### PR DESCRIPTION
**Pull request by minrk**
- only load metadata if a given extension package is enabled (closes #1177)
- module will be None, extension points will be empty if disabled. Version will be empty, though we could look it up _most_ of the time via `importlib_metadata` (module name != package name, etc.). I'm not sure how relevant the version number is for disabled extensions, though.
- unify use of traitlets, removing redundant use of public properties exposing identical private attributes, when public attributes will do (no change to api).

### CODE REVIEW

**Comment by yuvipanda** [comment]
Thanks a lot for working on this, @minrk!

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by xinliupitt** [comment]
I have a question. Is "only load metadata if a given extension package is enabled" by default in this release:  
https://github.com/jupyter-server/jupyter_server/releases/tag/v2.2.0

We don't need any flags to enable it, right?

**Comment by xinliupitt** [comment]
Another question: if I directly install Jupyterlab by any method [here](https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html), will it automatically include the latest v2.2.0 jupyter server release?

**Comment by blink1073** [comment]
You do not need any flags to enable this functionality.  Yes, if you install JupyterLab 3.5+ then `pip`/`conda`/`mamba` should also install Jupyter Server 2.2, unless the installer decides to use a local cached version.  If you run `pip list` (or `conda list`) you can check which version got installed.  If it is less than Server 2.2, you can run `pip install --upgrade jupyter_server` or `conda install jupyter_server==2.2`.

**Comment by xinliupitt** [comment]
Thanks a lot! I encountered an issue during installation. That is, I put `jupyter_server==2.2` in my requirement file. However, the log shows only some 2.0.0 versions are available
```
ERROR: Could not find a version that satisfies the requirement jupyter_server==2.2 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.3.0, 1.0.0rc0, 1.0.0rc1, 1.0.0rc2, 1.0.0rc3, 1.0.0rc4, 1.0.0rc5, 1.0.0rc6, 1.0.0rc7, 1.0.0rc8, 1.0.0rc9, 1.0.0rc10, 1.0.0rc11, 1.0.0rc12, 1.0.0rc13, 1.0.0rc14, 1.0.0rc15, 1.0.0rc16, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10, 1.0.11, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.7.0a1, 1.7.0a2, 1.7.0, 1.8.0, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.11.1, 1.11.2, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.2, 1.13.3, 1.13.4, 1.13.5, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.15.5, 1.15.6, 1.16.0, 1.17.0, 1.17.1, 1.18.0, 1.18.1, 1.19.0, 1.19.1, 1.21.0, 1.23.0, 1.23.1, 1.23.2, 1.23.3, 1.23.4, 1.23.5, 2.0.0a0, 2.0.0a1, 2.0.0a2, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0rc3)
ERROR: No matching distribution found for jupyter_server==2.2
Traceback (most recent call last):
  File "/home/kbuilder/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/kbuilder/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 495, in main
    execute(sys.argv[1:])
  File "/home/kbuilder/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 485, in execute
    cache_dir=args.cache_dir,
  File "/home/kbuilder/miniconda3/lib/python3.7/site-packages/conda_build/api.py", line 189, in build
    variants=variants
  File "/home/kbuilder/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 3102, in build_tree
    notest=notest,
  File "/home/kbuilder/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 2210, in build
    cwd=src_dir, stats=build_stats)
  File "/home/kbuilder/miniconda3/lib/python3.7/site-packages/conda_build/utils.py", line 402, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/home/kbuilder/miniconda3/lib/python3.7/site-packages/conda_build/utils.py", line 382, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/kbuilder/miniconda3/conda-bld/dlenv-base_1675280443233/work/conda_build.sh']' returned non-zero exit status 1.
```

Does this mean 2.2.0 hasn't been released?

**Comment by kevin-bates** [comment]
Hi @xinliupitt - the conda-forge PR was merged 7 hours ago, so it may still be propagating (or however that works). 

FWIW, I just now issued:
```bash
$ conda install -c conda-forge jupyter_server==2.2.0
```
and it appears to have installed:
```
$ conda list jupyter_server
# packages in environment at /opt/miniconda3/envs/elyra-dev:
#
# Name                    Version                   Build  Channel
jupyter_server            2.2.0              pyhd8ed1ab_0    conda-forge
```
so I suspect you hit that window in which things were still getting "into position".

**Comment by xinliupitt** [comment]
Thanks a lot! Finally I find I need JupyterLab 3.5 + Python 3.8 as the dependencies, in order to upgrade to jupyter-server 2.2.0.

**Comment by blink1073** [comment]
@meeseeksdev please backport to 1.x

**Pull request merged**
