### PR TITLE
Test python 3.11 on ubuntu

### PR DESCRIPTION
**Pull request by blink1073**
Start testing the RC release of Python 3.11

### CODE REVIEW

**Comment by blink1073** [comment]
Nope, looks like we're blocked on `pyzmq` building on Python 3.11.:

```
             gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DHAVE_SYS_UN_H=1 -Ibundled/zeromq/include -Izmq/utils -I/opt/hostedtoolcache/Python/3.11.0-beta.1/x64/include/python3.11 -c zmq/backend/cython/_device.c -o build/temp.linux-x86_64-cpython-311/zmq/backend/cython/_device.o
            zmq/backend/cython/_device.c:217:12: fatal error: longintrepr.h: No such file or directory
              217 |   #include "longintrepr.h"
                  |            ^~~~~~~~~~~~~~~
            compilation terminated.
            error: command '/usr/bin/gcc' failed with exit code 1
            [end of output]
```

**Comment by blink1073** [comment]
I opened https://github.com/zeromq/pyzmq/issues/1697

**Comment by davidbrochart** [comment]
> What even does `no-deps` mean?

You mean `--no-deps` has no effect on Python 3.11?

**Comment by blink1073** [comment]
Hmm, let's test that theory...

**Comment by blink1073** [comment]
Same thing with Python 3.10.  Let me try editable mode again.

**Comment by blink1073** [comment]
Next try is building the sdist first and then installing from that with `--pre`.

**Comment by blink1073** [comment]
Okay, this seems like a bug in `flit` or `pip`.  I don't see why we should be picking up run time dependencies when building a `wheel` or `sdist`.

**Comment by blink1073** [comment]
Blocked on https://github.com/yaml/pyyaml/issues/630

**Pull request merged**
