### PR TITLE
Switch to hatch build plugin

### PR DESCRIPTION
**Pull request by blink1073**
- Uses new [hatch_jupyter_builder](https://github.com/blink1073/hatch_jupyter_builder) plugin

### CODE REVIEW

**Comment by blink1073** [comment]
This is ready for discussion at tomorrow's meeting.

**Review by willingc — APPROVED** [review]
Ooh nice @blink1073. I didn't know this existed.

**Comment by blink1073** [comment]
Thanks @willingc!  The conversion is still a WIP, based on needs in https://github.com/jupyterlab/jupyterlab/pull/12606 and https://github.com/jupyter/notebook/pull/6425.

**Comment by blink1073** [comment]
Once we have a solution and migration script/guide for extension authors, I'll write a blog post.

**Pull request merged**
