### PR TITLE
Remove terminals in favor of jupyter_server_terminals extension

### PR DESCRIPTION
**Pull request by Zsailer**
Not ready for review yet. I'll ping reviewers here once it's ready.

This is an early preview of removing terminals from jupyter_server in favor of offering terminals as a Jupyter Server extension. This work was started by @blink1073 in [jupyter-server/jupyter_server_terminals](https://github.com/jupyter-server/jupyter_server_terminals).

### CODE REVIEW

**Comment by Wh1isper** [comment]
Just a reminder if TerminalManager should be configurable, like several KernelManager; Terminal extensionmay also need to be adjusted to support this feature. @blink1073 
Thank you!

**Comment by blink1073** [comment]
@Wh1isper, yep, that is handled here: https://github.com/jupyter-server/jupyter_server_terminals/pull/2/files#diff-686b7a6f17e88cd5881544d8ce0bfc4e4224283a68597c33551bbb886136b335R32

**Comment by Wh1isper** [comment]
> @Wh1isper, yep, that is handled here: https://github.com/jupyter-server/jupyter_server_terminals/pull/2/files#diff-686b7a6f17e88cd5881544d8ce0bfc4e4224283a68597c33551bbb886136b335R32

cool！

**Comment by blink1073** [comment]
Kicking CI to pick up the released package

**Comment by blink1073** [comment]
We need a bit more shimming to get `nbclassic` downstream test to pass, and we need to add auth per https://github.com/jupyter-server/jupyter_server_terminals/issues/10

**Comment by blink1073** [comment]
Plus there are two tests that hang that are temporarily skipped

**Comment by blink1073** [comment]
Kicking CI

**Comment by blink1073** [comment]
Looks like the last piece we need is https://github.com/jupyter-server/jupyter_server_terminals/pull/15.

I'll pick this back up on Monday.

**Comment by blink1073** [comment]
Great success!

**Comment by Zsailer** [comment]
Nice work, @blink1073!

**Comment by blink1073** [comment]
With the most recent push, we no longer have to use the awkward `initialize()` that is currently in [`jupyterlab_server`](https://github.com/jupyterlab/jupyterlab_server/blob/762e242c62c1b0949e0304e28cd6c8da93d615a2/jupyterlab_server/settings_handler.py#L19) and [`jupyter_server_terminals`](https://github.com/jupyter-server/jupyter_server_terminals/blob/fb6c98df3f90ca6ffc092532bffe6895b3f11bd2/jupyter_server_terminals/handlers.py#L24), but we are tolerant to their existence.  

The one place we might hit a circular call stack is if the subclass `initialize()` has no other arguments and calls ` ExtensionHandlerMixin.initialize(self, name)` directly.

**Pull request merged**
