### PR TITLE
fix Content-Type header set for SVG files

### PR DESCRIPTION
**Pull request by mbektas**
Content-Type for SVG icon is properly set in [GatewayResourceHandler](https://github.com/jupyter-server/jupyter_server/blob/main/jupyter_server/gateway/handlers.py#L293) but overridden in the base handler to `application/json`. This change prevents overriding Content-Type if previously set.

Fixes https://github.com/jupyter-server/jupyter_server/issues/1216

### CODE REVIEW

**Comment by kevin-bates** [comment]
Hi @mbektas - thank you for identifying the issue and providing a pull request.  In looking into this just now (sorry, I hadn't seen your PR), I came to roughly the same conclusion about where the fix is located.  I also added a test case since resources from a gateway are handled a bit differently than local resources (in that they don't go through the static file handler).  Would you mind if I pushed the test update to your branch as part of this PR?

**Comment by mbektas** [comment]
hi @kevin-bates , sure, please feel free to push any updates as necessary.

**Comment by kevin-bates** [comment]
(Sorry for the delay.  I just pushed the test update.)

**Comment by kevin-bates** [comment]
Hi @mbektas - I think the test failure is legitimate. When I step through the `test_api.py::test_get_status` test with a debugger, I see `self._headers['Content-Type'] == 'text/html'`, so `application/json` never gets set.  Given this appears to be the only test failure, it might be okay to set the mime-type in that particular handler.

FWIW, the way I resolved this was to [add a `set_content_type` kwarg that callers set to override the `application/json`](https://github.com/kevin-bates/jupyter_server/pull/16/files) content-type, this way all changes are explicit since the caller (`GatewayResourceHandler`) has to request the override.

**Comment by mbektas** [comment]
@kevin-bates I am not that familiar with this codebase and came up with my solution after a quick debugging. Your solution looks more explicit and safe. I wouldn't mind closing this PR and going with your changes.

**Comment by kevin-bates** [comment]
Ok - that sounds good.  I would like to add you as a co-author in my PR, do you mind if I do that?

**Comment by kevin-bates** [comment]
Closing in favor of #1219.  Thanks for your help on this @mbektas!

**Pull request closed without merging**
