### PR TITLE
Added Logs for get_os_path closes issue

### PR DESCRIPTION
**Pull request by jayeshsingh9767**
closes issue [jupyter/notebook#857](https://github.com/jupyter/notebook/issues/857)

Changes made: added **self.log.debug("Reading path from disk: %s", path)** in filemanager.py in jupyter_server

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks @jayeshsingh9767!  It looks like we could put the debug log in the `_get_os_path` and handle all of the cases you added.

**Comment by jayeshsingh9767** [comment]
@blink1073 Thanks for the Quick Review, initially I too though so but I was not sure if self.log object is available inside [fileio.py](https://github.com/jupyter-server/jupyter_server/blob/main/jupyter_server/services/contents/fileio.py) will try out logging inside `_get_os_path` and check if all Testcases pass.

**Comment by blink1073** [comment]
The typing failures are unrelated, I'll handle those in a follow up PR.

**Review by blink1073 — APPROVED** [review]
Thank you!

**Comment by blink1073** [comment]
Oh actually, the lint is related, ha!  I'll push the updates.

**Comment by jayeshsingh9767** [comment]
Thanks @blink1073

**Comment by Carreau** [comment]
Congrats on closing a 7 years old issue ! 🥳

**Pull request merged**
