### PR TITLE
Add mypy check

### PR DESCRIPTION
**Pull request by blink1073**
Minimal typings support, mostly as a linter for now.

Uses new typings from [`jupyter_client`](https://github.com/jupyter/jupyter_client/pull/766).

I'm working on shipping minimal typings with traitlets and jupyter_core as well.

### CODE REVIEW

**Comment by Zsailer** [comment]
I think this is going to cause some pain for other PRs that will need to rebase. Maybe we should wait until (at least) identity is merged?

**Comment by blink1073** [comment]
Sounds fair, will mark as 2.0

**Comment by blink1073** [comment]
This is ready now

**Comment by blink1073** [comment]
I plan to merge this and cut the first alpha release tomorrow.

**Comment by Zsailer** [comment]
Do you think we should backport these changes?

I ask, because if we merge this and don't backport it, do you think it will cause issues for future backports? It seems like future backports might have conflicts with changes here and cause meeseeks to choke.

**Comment by blink1073** [comment]
Good point, I'll take care of the backporting of this one.

**Comment by blink1073** [comment]
@meeseeksdev please backport to 1.x

**Pull request merged**
