### PR TITLE
pytest: package conftest

### LINKED ISSUE #563: Cannot run tests when installed from PyPI
## Description

`pip install jupyter_server[test]` doesn't allow to run the tests.

## Reproduce

1. `mamba create -n jupyter_server jupyter_server`
2. `conda activate jupyter_server`
3. ` pytest --pyargs jupyter_server`
4. Tests are failing because the fixtures cannot be found.

`conftest.py` is at the root of the repository and is not included in the package.

## Expected behavior

The tests are part of the package, so we should be able to run them.

## Context

- Operating System and version: Ubuntu 21.04
- Browser and version: N/A
- Jupyter Server version: 1.10.1

### PR DESCRIPTION
**Pull request by oliver-sanders**
closes #563

* Package the conftest file.
* This changes the test command to `pytest jupyter_server`.
* Import the `jupyter_server.conftest` in the examples to inherit the plugin.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
* Windows tests failing as expected.
* MacOS PyPy tests failing at the installation phase trying to build `pyzmq`.

**Comment by blink1073** [comment]
Bumping to pick up the CI fixes from #571

**Review by blink1073 — APPROVED** [review]
Thank you!

**Review by Zsailer — APPROVED** [review]
Thanks, @oliver-sanders. :+1:

**Pull request merged**
