### PR TITLE
Fix server-extension paths (3rd time's the charm)

### PR DESCRIPTION
**Pull request by minrk**
reverts #732 with fix for MultipleInstanceErrors

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]
Thanks again!

**Comment by minrk** [comment]
❤️ sorry for the headaches!

**Comment by blink1073** [comment]
> ❤️ sorry for the headaches!

Haha no worries, this is a tricky one

**Comment by blink1073** [comment]
Drat, I merged this too early it seems, it hadn't finished the `Install from SDist and Test` job, which now hangs at exit.   I'm not going to hold up the release though.

**Pull request merged**
