### PR TITLE
docs: list server extensions

### PR DESCRIPTION
**Pull request by oliver-sanders**
I thought it would be good to list some examples of Jupyter Server extensions on the website.

This could help:
* Make folks aware of the multifaceted applications that Jupyter Server is capable of supporting (much more than just notebooks!).
* Provide a handy reference for extension developers (I found the Jupyter Lab source code an invaluable resource).
* Raise awareness of the extensions already out there (I'm sure there are more that I'm not aware of).

I've listed the server extensions I'm aware of, including my own if you're happy to list it, in descending order of GH stars along with their GH project descriptions. Let me know if there are others I should add. My suggestion is to keep it to actively maintained Jupyter Server extensions (not downstream extensions e.g. Jupyter Lab extensions).

### CODE REVIEW

**Comment by blink1073** [comment]
Very nice!  I'd suggest adding:

https://github.com/jupyter-server/jupyter-resource-usage
https://github.com/jupyter-server/jupyter-scheduler
https://github.com/jupyterlite/jupyterlite

**Comment by oliver-sanders** [comment]
> Ah, good point, it is a server app but not an extension.

It is using the Jupyter Server APIs though right?

It would be good to raise awareness of this pattern too.

**Comment by Zsailer** [comment]
> It is using the Jupyter Server APIs though right?

Not exactly. It [mocks the Server APIs](https://github.com/jupyterlite/jupyterlite/blob/main/packages/server-extension/src/index.ts) entirely in the frontend by replacing JupyterLab's `ServiceManager` with a custom implementation and mocking all responses from the server.

**Comment by oliver-sanders** [comment]
Added jupyter-resource-usage & jupyter-scheduler

**Review by blink1073 — APPROVED** [review]
Thanks very much!

**Pull request merged**
