### PR TITLE
Handle newer jupyter_events wants string version, drop 3.8

### PR DESCRIPTION
**Pull request by Carreau**
The new Jupyter_events that deals with python-json-logger issue also fixed and issue where version should be string (as it can have minor versions like 1.1 for example).

The new Jupyter_events does not have support for python 3.8, so drop it as well; and propagate all the type changes.

### CODE REVIEW

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
Looks like this could be released in a `2.15.0` rather than a patch release?

**Comment by Carreau** [comment]
Thanks !

**Comment by minrk** [comment]
published 2.15.0 with this

**Comment by jtpio** [comment]
Thanks @minrk!

**Comment by Carreau** [comment]
thanks !

**Pull request merged**
