### PR TITLE
update LICENSE

### PR DESCRIPTION
**Pull request by dcsaba89**

### CODE REVIEW

**Comment by dcsaba89** [comment]
Hi @blink1073, created a LICENSE file using Github's official BSD 3-Clause License template (as the idea to simply rename the file did not work, maybe because the original CHANGE.md was not created with that templace), but I kept most of the wording from the original CHANGE.md

**Review by blink1073 — APPROVED** [review]
Thanks again, let's see if it works this time!  :smile:

**Comment by blink1073** [comment]
Hmm, it still does not show up in the UI.   It seems it does not like the extra content at the bottom, which we can't remove.

**Comment by dcsaba89** [comment]
Could you move it somewhere else? Would it be possible?

**Comment by blink1073** [comment]
I don't think so, no.  I think we've done as much as we can.  We have a compliant license, we can't compromise it to conform to the GitHub UI.

**Pull request merged**
