### PR TITLE
Fix port selection

### LINKED ISSUE #1170: wrong jupyter server port number in a specific situation
## Description

I can't start the new `jupyter lab` server on a given port when the server that was previously running on this port has just been shut down. Previously, when I was using version 1.23.4, this error did not occur. Moreover, when I wait a bit (let's say 5 min) after shutting down `jupyter lab` server, I am able to run it on the desired port.

## Reproduce

1. create conda environment `conda create -n env_name`
2. activate the environment `conda activate env_name`
3. install jupyter lab `conda install jupyterlab -c conda-forge`
4. start jupyter lab server on specific port `jupyter lab --port 1234`
5. after a few seconds, close the jupyter lab server `Ctrl-C`
6. start jupyter lab server again on the same port `jupyter lab --port 1234`
7. `jupyter lab` server is running on port 1235 instead of 1234.

## Expected behavior

After shutting down the jupyter lab server running on port 1234, it is possible to restart the jupyter lab server on the same specified port 1234.

## Context

- Operating System and version: Ubuntu 22.04.1 LTS
- Browser and version: Mozilla Firefox 108.0.2 (64-bit)
- Jupyter Server version: 2.0.6

<details><summary>Command Line Output</summary>
<pre>
jupyter lab --port 1234
[I 2023-01-10 09:58:23.315 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-01-10 09:58:23.317 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-01-10 09:58:23.318 ServerApp] nbclassic | extension was successfully linked.
[I 2023-01-10 09:58:23.410 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-01-10 09:58:23.492 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-01-10 09:58:23.492 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-01-10 09:58:23.493 LabApp] JupyterLab extension loaded from /home/jakub/miniconda3/envs/test_2/lib/python3.11/site-packages/jupyterlab
[I 2023-01-10 09:58:23.493 LabApp] JupyterLab application directory is /home/jakub/miniconda3/envs/test_2/share/jupyter/lab
[I 2023-01-10 09:58:23.494 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-01-10 09:58:23.495 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-01-10 09:58:23.495 ServerApp] Serving notebooks from local directory: /home/jakub/Desktop
 [I 2023-01-10 09:58:23.495 ServerApp] Jupyter Server 2.0.6 is running at:
[I 2023-01-10 09:58:23.495 ServerApp] http://localhost:1234/lab?token=46f218262a185ea765bee8f2ee09a362b06a7289c15649c1
[I 2023-01-10 09:58:23.495 ServerApp]  or http://127.0.0.1:1234/lab?token=46f218262a185ea765bee8f2ee09a362b06a7289c15649c1
[I 2023-01-10 09:58:23.495 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-01-10 09:58:23.514 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/jakub/.local/share/jupyter/runtime/jpserver-5834-open.html
    Or copy and paste one of these URLs:
        http://localhost:1234/lab?token=46f218262a185ea765bee8f2ee09a362b06a7289c15649c1
     or http://127.0.0.1:1234/lab?token=46f218262a185ea765bee8f2ee09a362b06a7289c15649c1
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[W 2023-01-10 09:58:26.008 LabApp] Could not determine jupyterlab build status without nodejs
[I 2023-01-10 09:58:44.267 ServerApp] Shutting down on /api/shutdown request.
[I 2023-01-10 09:58:44.267 ServerApp] Shutting down 4 extensions
(test_2) jakub@jakub:~/Desktop$ jupyter lab --port 1234
[I 2023-01-10 09:59:03.907 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-01-10 09:59:03.909 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-01-10 09:59:03.911 ServerApp] nbclassic | extension was successfully linked.
[I 2023-01-10 09:59:03.999 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-01-10 09:59:04.079 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-01-10 09:59:04.080 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-01-10 09:59:04.080 LabApp] JupyterLab extension loaded from /home/jakub/miniconda3/envs/test_2/lib/python3.11/site-packages/jupyterlab
[I 2023-01-10 09:59:04.080 LabApp] JupyterLab application directory is /home/jakub/miniconda3/envs/test_2/share/jupyter/lab
[I 2023-01-10 09:59:04.081 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-01-10 09:59:04.082 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-01-10 09:59:04.082 ServerApp] The port 1234 is already in use, trying another port.
[I 2023-01-10 09:59:04.083 ServerApp] Serving notebooks from local directory: /home/jakub/Desktop
[I 2023-01-10 09:59:04.083 ServerApp] Jupyter Server 2.0.6 is running at:
[I 2023-01-10 09:59:04.083 ServerApp] http://localhost:1235/lab?token=9aaba670f7306be9d99c65a31f069521ab0f9a1717a821f7
[I 2023-01-10 09:59:04.083 ServerApp]  or http://127.0.0.1:1235/lab?token=9aaba670f7306be9d99c65a31f069521ab0f9a1717a821f7
[I 2023-01-10 09:59:04.083 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-01-10 09:59:04.101 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/jakub/.local/share/jupyter/runtime/jpserver-6104-open.html
    Or copy and paste one of these URLs:
        http://localhost:1235/lab?token=9aaba670f7306be9d99c65a31f069521ab0f9a1717a821f7
     or http://127.0.0.1:1235/lab?token=9aaba670f7306be9d99c65a31f069521ab0f9a1717a821f7
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[W 2023-01-10 09:59:06.578 LabApp] Could not determine jupyterlab build status without nodejs
[I 2023-01-10 09:59:18.427 ServerApp] Shutting down on /api/shutdown request.
[I 2023-01-10 09:59:18.428 ServerApp] Shutting down 4 extensions
</pre>
</details>

## Additional information

I've tried reproducing this step on Windows as well as Github Action CI and the error I described above doesn't occur here. In addition, I checked on Ubuntu 22.04.1 what will happen when I change the `jupyter_server` version from 2.0.6 to 1.23.4. After this change I was able to start the servers on the right ports.

## Possible solution

The problem seems to disappear when I replace `_find_http_port` with `_bind_http_server_tcp` in `serverapp.py` (I manually edited `serverapp.py` after downloading the `jupyter_server` 2.0.6 package) which was present in `jupyter_server` 1.23.4. After this change, I can start the servers on the right ports on Ubuntu 22.04.01.

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #1170, by using the same `bind_sockets` function as is later used to start the http server.

### CODE REVIEW

**Comment by blink1073** [comment]
@kevin-bates should we do something similar in [`jupyter_client`](https://github.com/jupyter/jupyter_client/blob/df84040b05d4eb3a9a9530de8076b0f7c09f9c10/jupyter_client/connect.py#L688)?

**Comment by blink1073** [comment]
The tornado util function appears to be more robust.

**Comment by kevin-bates** [comment]
> @kevin-bates should we do something similar in [jupyter_client](https://github.com/jupyter/jupyter_client/blob/df84040b05d4eb3a9a9530de8076b0f7c09f9c10/jupyter_client/connect.py#L688)?

I think this makes sense.  Are we confident the `SO_LINGER` portion is unnecessary?  This also more closely binds us (pun intended) to tornado - although its exclusion would likely occur in an entirely different code base - but wanted to mention that as a possible deterrent.

**Comment by blink1073** [comment]
Yeah, I don't think we need LINGER because we aren't actually sending any messages on this socket.  We could always inline the method with attribution if we ever decide to move off of `tornado`.

**Comment by blink1073** [comment]
Actually, I don't think we need this logic in client, since we're asking the OS to give us a port, not attempting to use a specific one.

**Pull request merged**
