### PR TITLE
Import ensure_async from jupyter_core

### PR DESCRIPTION
**Pull request by davidbrochart**
Needs https://github.com/jupyter/jupyter_core/pull/315.

### CODE REVIEW

**Comment by blink1073** [comment]
I think `jupyter_core>=4.12!~5.0`

**Comment by davidbrochart** [comment]
Should we just pin `jupyter_core>=4.12,<5`, and when we switch to v5 we'll pin `jupyter_core>=5.1`?

**Comment by blink1073** [comment]
> Should we just pin jupyter_core>=4.12,<5, and when we switch to v5 we'll pin jupyter_core>=5.1?

I'd rather not pin, since we want folks to try core 5.x and its new features.

**Comment by blink1073** [comment]
I'll have to update the min versions script in maintainer tools though to handle more complex cases like this...

**Comment by bollwyvl** [comment]
Working on the conda-forge package... what _exactly_ is intended by the `jupyter_core` pin?

**Comment by davidbrochart** [comment]
`jupyter-core` v4.12 and v5.1 have the `ensure_async` and `run_sync` common functions that are used in `jupyter-server`, `jupyter-client` and `nbclient`. Each one was previously reimplementing the logic separately.

**Comment by davidbrochart** [comment]
Sounds good, but maybe `!=5.0.*` instead of `!=5.0.0`?
And I thought we were not pinning upper bounds any more?

**Comment by bollwyvl** [comment]
Here's the line in question:
https://github.com/conda-forge/jupyter_server-feedstock/pull/106#pullrequestreview-1208349911

**Comment by transaxon** [comment]
Looks as if this may have caused an error under Ubuntu 20.04 running under WSL2 

$  ImportError: cannot import name 'ensure_async' from 'jupyter_core.utils'

**Comment by davidbrochart** [comment]
What version of `jupyter_core` do you have?

**Comment by transaxon** [comment]
mjw@TRANSAXON-SEROTONIN:~$ jupyter --version
Selected Jupyter core packages...
IPython          : 8.4.0
ipykernel        : 6.13.0
ipywidgets       : 8.0.2
jupyter_client   : 7.3.1
jupyter_core     : 4.10.0
jupyter_server   : 2.0.1
jupyterlab       : not installed
nbclient         : not installed
nbconvert        : not installed
nbformat         : 5.7.0
notebook         : 6.0.3
qtconsole        : 5.3.0
traitlets        : 5.2.2

**Comment by transaxon** [comment]
It's not at all clear to me why it thinks jupyterlab nbclient and nbconvert aren't installed

**Comment by davidbrochart** [comment]
`jupyter-server 2.0.1` requires [jupyter_core>=4.12](https://github.com/jupyter-server/jupyter_server/blob/7b6fb443b2f0fbf69a559d64c4e4aea6bba22e00/pyproject.toml#L34), try creating a new environment.

**Pull request merged**
