### PR TITLE
Authorization

### PR DESCRIPTION
**Pull request by davidbrochart**
This is a rebase of @Zsailer's PR #165

### CODE REVIEW

**Comment by echarles** [comment]
Awesome! What are the plans with this?

**Comment by echarles** [comment]
I see on the previous Pr comments like https://github.com/jupyter-server/jupyter_server/pull/165/files#r364461658 - would be good to not forget them

**Comment by davidbrochart** [comment]
> Awesome! What are the plans with this?

I think Zach's PR was a nice solution for supporting authorization, should we push it forward?

**Comment by kevin-bates** [comment]
Given the original PR is marked WIP could we discuss this at tomorrow's [server dev meeting](https://github.com/jupyter-server/team-compass#weekly-team-meetings) before moving forward?  We may also want to look at rebasing on the original PR so as to preserve comment history.

**Comment by davidbrochart** [comment]
I can join the meeting and discuss this PR and Zach's original plans.

**Comment by davidbrochart** [comment]
I pushed this PR back to Zach's original PR #165, we'll work there from now on, at least to keep it up to date in case we want to merge it.

**Pull request closed without merging**
