### PR TITLE
Add top-level LICENSE file

### PR DESCRIPTION
**Pull request by dcsaba89**
Add top-level LICENSE file

### CODE REVIEW

**Comment by blink1073** [comment]
Hi @dcsaba89, our top level license file is called [COPYING.md](https://github.com/jupyter-server/jupyter_server/blob/main/COPYING.md) and is included in our distributed [package](https://github.com/jupyter-server/jupyter_server/blob/f3fe168bc3a30051d021953e6e3631c794675ef7/pyproject.toml#L9).

**Comment by dcsaba89** [comment]
Hi @blink1073, that file could not be recognized as a license file and causing issues for us, that is why I commited a new license file based on the following guide: 
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Please take a look at other repositories , the license file is in the root of the repository and called LICENSE or maybe LICENSE.txt

https://github.com/pandas-dev/pandas/blob/main/LICENSE
https://github.com/numpy/numpy/blob/main/LICENSE.txt
https://github.com/jupyter-widgets/ipywidgets/blob/main/LICENSE

And you can see a badge on the top of the pages that shows the license itself and the associated permissions, limitations and conditions as well. 

However you cannot see this badge for your top level license file
https://github.com/jupyter-server/jupyter_server/blob/main/COPYING.md

This change would help significantly to update jupyter server more frequently for our python projects.

**Comment by blink1073** [comment]
I think it is fine to rename the top level file to `LICENSE`, if you'd like to do that instead.  Can you elaborate on what other issue this is causing other than the GitHub UX?

**Comment by dcsaba89** [comment]
Thanks @blink1073, created a new PR [https://github.com/jupyter-server/jupyter_server/pull/1196] to rename COPYING.md to LICENSE as you advised, but I am not sure how the original COPYING.md was created

**Comment by blink1073** [comment]
Closing in favor of #1196

**Pull request closed without merging**
